//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebOrganizer.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class FinishedTask
    {
        public int TaskID { get; set; }
        [Display(Name = "Done")]
        public string TaskDescription { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Start")]
        public Nullable<System.DateTime> StartDate { get; set; }
        [DataType(DataType.Date)]
        [Display(Name = "Finish")]
        public Nullable<System.DateTime> FinishDate { get; set; }
        [Display(Name = "Comments")]
        public string Category { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
